---
# tasks file for configuration
    -
      name: "Update Packages on Launched Instances"
      become: true
      become_user: root
      yum:
        name: "*"
        state: latest
    -
      name: "Install required Packages on Launched Instances"
      become: true
      become_user: root
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - wget
        - git
        - postgresql-contrib
        - ksh
        - zip
    -
      name: "Make directory for Sqoop Lib"
      become: true
      become_user: root
      file: path=/usr/lib/sqoop/lib state=directory
    -
      name: "Install postgresql92 driver"
      become: true
      become_user: root
      command: yum -y install postgresql92-server.x86_64 postgresql92-contrib.x86_64 postgresql92-devel.x86_64
      ignore_errors: true
    -
      name: "Install psycopg2"
      become: true
      become_user: root
      command: pip install psycopg2==2.7.5
    -
      name: "Make directory for Postgresql"
      become: true
      become_user: root
      file: path=/opt/postgresql/bin/ state=directory
    -
      name: "Copy contents for Postgresql"
      become: true
      become_user: root
      command: "cp /usr/bin/psql /opt/postgresql/bin/"
    -
      name: "Stop Postfix Service"
      become: true
      become_user: root
      shell: "/usr/sbin/postfix stop"
    -
      name: "Start Postfix Service"
      become: true
      become_user: root
      command: "/usr/sbin/postfix start"
